##NATURAL LANGUAGE PROSESSING

In [ ]:
import pandas as pd
import nltk
from nltk.tokenize import word_tokenize,sent_tokenize
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

In [ ]:
df=pd.read_csv('/content/nlp_dataset.csv')
df

                                                Text
0  Natural Language Processing is a fascinating f...
1  It bridges the gap between humans and machines...
2  NLP techniques are widely used in applications...
3  Machine translation and speech recognition are...
4  Despite its advancements, NLP faces challenges...
5  Continuous research and innovation are improvi...
6  The potential of NLP is vast, making it essent...

In [ ]:
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('omw-1.4')
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

True

In [ ]:
stop_words=set(stopwords.words('english'))
print(stop_words)
lemmatizer=WordNetLemmatizer()

{'its', 'doing', 'own', 'some', 'until', 'did', 'shan', 'both', 'yours', 'will', 'few', 'to', "she'd", 'your', 'where', 'if', 'doesn', 'mustn', "shouldn't", 'can', 'aren', "don't", "needn't", "you'll", "he'll", 'too', 't', "weren't", 'should', "it's", 'my', 'our', 'herself', 'their', 'hers', 'yourself', 'below', 'ain', "we'd", 'why', 'again', 'not', 'for', 'those', 'she', "we're", "isn't", 'shouldn', 'her', 'each', 'his', 'with', "you'd", 'same', 'because', 'through', "mightn't", 'me', 'then', 'has', 'over', 'am', 'further', 'from', 'yourselves', 'once', 'm', 'o', 'll', 'that', 'more', 'any', 'no', 'so', 'hadn', 'myself', 'you', 'him', 'an', 'don', 'd', "doesn't", 'now', 'are', 'who', "didn't", 'between', "aren't", 'at', "it'd", 'were', 'which', "you've", 'on', 'themselves', 'having', 'other', 'while', 'there', 'ma', 'theirs', 'hasn', 'before', 'only', 'itself', "couldn't", 'most', 'a', 'does', "she'll", 'i', "they'll", "we've", 've', 'into', 'all', 'is', 'be', "mustn't", 'they', "he's", 'wouldn', 'whom', "i'll", "he'd", 'won', 'or', 's', "they've", "wouldn't", 'ourselves', 'than', 'how', 'of', 'the', 'as', 'very', 'weren', 'y', 'above', 'couldn', 'here', 'but', 'been', "she's", 'when', 'after', 'have', 're', 'during', 'we', "they'd", 'nor', 'needn', 'what', 'this', 'such', 'it', "shan't", 'was', "you're", "i've", 'about', 'do', "i'm", "i'd", 'by', "that'll", 'down', 'in', 'these', 'out', "hasn't", "haven't", "won't", 'and', 'isn', 'them', 'just', "they're", 'mightn', 'under', 'wasn', 'had', 'up', 'ours', "hadn't", 'off', 'himself', 'he', 'didn', 'being', "we'll", 'haven', 'against', "should've", "wasn't", "it'll"}

In [ ]:
def process_text(text):
  word_tokens=word_tokenize(text)
  filtered_tokens=[word for word in word_tokens if word.lower() not in stop_words]
  lemmatized_tokens=[lemmatizer.lemmatize(word.lower()) for word in filtered_tokens]

  return{
      'original_Text':text,
      'word_Tokens':word_tokens,
      'filtered_Tokens':filtered_tokens,
      'Lemmatized_Tokens':lemmatized_tokens
  }

In [ ]:
  results=df['Text'].apply(process_text)

  processed_df=pd.DataFrame(results.tolist())

  print(processed_df.head())


  processed_file_path="processed_nlp_dataset.csv"
  processed_df.to_csv(processed_file_path,index=False)
  print(f"Processed data saved to {processed_file_path}")

                                       original_Text  \
0  Natural Language Processing is a fascinating f...
1  It bridges the gap between humans and machines...
2  NLP techniques are widely used in applications...
3  Machine translation and speech recognition are...
4  Despite its advancements, NLP faces challenges...

                                         word_Tokens  \
0  [Natural, Language, Processing, is, a, fascina...
1  [It, bridges, the, gap, between, humans, and, ...
2  [NLP, techniques, are, widely, used, in, appli...
3  [Machine, translation, and, speech, recognitio...
4  [Despite, its, advancements, ,, NLP, faces, ch...

                                     filtered_Tokens  \
0  [Natural, Language, Processing, fascinating, f...
1  [bridges, gap, humans, machines, enabling, com...
2  [NLP, techniques, widely, used, applications, ...
3  [Machine, translation, speech, recognition, co...
4  [Despite, advancements, ,, NLP, faces, challen...

                                   Lemmatized_Tokens
0  [natural, language, processing, fascinating, f...
1  [bridge, gap, human, machine, enabling, comput...
2  [nlp, technique, widely, used, application, ch...
3  [machine, translation, speech, recognition, co...
4  [despite, advancement, ,, nlp, face, challenge...
Processed data saved to processed_nlp_dataset.csv

In [ ]:
df

                                                Text
0  Natural Language Processing is a fascinating f...
1  It bridges the gap between humans and machines...
2  NLP techniques are widely used in applications...
3  Machine translation and speech recognition are...
4  Despite its advancements, NLP faces challenges...
5  Continuous research and innovation are improvi...
6  The potential of NLP is vast, making it essent...

In [ ]:
results

0    {'original_Text': 'Natural Language Processing...
1    {'original_Text': 'It bridges the gap between ...
2    {'original_Text': 'NLP techniques are widely u...
3    {'original_Text': 'Machine translation and spe...
4    {'original_Text': 'Despite its advancements, N...
5    {'original_Text': 'Continuous research and inn...
6    {'original_Text': 'The potential of NLP is vas...
Name: Text, dtype: object